#!/usr/bin/env python

import warnings
#'with' isn't supported in python 2.5.2 on mtu.net with warnings.catch_warnings():
warnings.simplefilter("ignore")
import re
import os
import os.path
from subprocess import call
import sys
warnings.resetwarnings()

def clean_file(filename):
    f = file(filename)
    data=f.read()
    f.close()

    # remove block scripts
    p = re.compile(r'<script\b[^>]*>.*?</script>', re.DOTALL | re.IGNORECASE)
    data = p.sub('', data)

    # remove single line scripts
    p = re.compile(r'<script\b[^>]*/>', re.DOTALL | re.IGNORECASE)
    data = p.sub('', data)

    # remove link tags
    p = re.compile(r'<link\b[^>]*/>', re.DOTALL | re.IGNORECASE)
    data = p.sub('', data)

    new = file(filename, 'w')
    new.write(data)
    new.close()

if __name__ == "__main__":
    mypath = os.path.dirname(__file__)
    wiki_dir = os.path.join(mypath, "web", "wiki")
    if not os.path.exists(wiki_dir):
        os.mkdir(wiki_dir)

    print "Downloading wiki content"
    cmd='wget -R "*action=*" -I /apps/trac/fll-sw/wiki --page-requisites --html-extension --restrict-file-names=windows -P web/wiki -nH --cut-dirs=3 -k --mirror http://sourceforge.net/apps/trac/fll-sw/wiki'
    try:
        retcode = call(cmd, shell=True)
        if retcode < 0:
            print >>sys.stderr, "Error getting wiki, child was terminated by signal", -retcode
    except OSError, e:
        print >>sys.stderr, "Error getting wiki: ", e

    # now clean it
    print "Cleaning downloaded content"
    for root, dirs, files in os.walk(wiki_dir):
        for f in files:
            clean_file(os.path.join(root, f))
            
