#!/bin/sh

debug() { ! "${log_debug-false}" || log "DEBUG: $*" >&2; }
log() { printf '%s\n' "$*"; }
warn() { log "WARNING: $*" >&2; }
error() { log "ERROR: $*" >&2; }
fatal() { error "$*"; exit 1; }
mydir=$(cd "$(dirname "$0")" && pwd -L) || fatal "Unable to determine script directory"

if [ -z "${WORKSPACE}" ]; then
    fatal "WORKSPACE not defined, cannot continue"
fi

fllsw_root="${mydir}"/..

cd "${WORKSPACE}"
git_branch=$(git show -s --pretty=%d HEAD | awk -F, '{print $2}' | awk -F')' '{print $1}')
git_version=$(git describe --always)
log "BRANCH: ${git_branch} GIT_VERSION: ${git_version}"

# get wiki documentation
#cd "${fllsw_root}"/scoring/docs
#"${fllsw_root}"/scoring/scripts/markdown-to-html.py *.md \
#    || fatal "Error converting wiki documentation"

cd "${fllsw_root}"/scoring
./ant.sh dist || fatal "Error building distribution"

