#!/bin/sh

debug() { ! "${log_debug-false}" || log "DEBUG: $*" >&2; }
log() { printf '%s\n' "$*"; }
warn() { log "WARNING: $*" >&2; }
error() { log "ERROR: $*" >&2; }
fatal() { error "$*"; exit 1; }
mydir=$(cd "$(dirname "$0")" && pwd -L) || fatal "Unable to determine script directory"

if [ -z "${WORKSPACE}" ]; then
    fatal "WORKSPACE not defined, cannot continue"
fi

cd "${WORKSPACE}"

#clean up from previous run
git clean -xdf || fatal "Error cleaning workspace"

cd scoring


# setup version identifier
echo "app.version=devel-${BUILD_ID}" > override.properties

# get wiki documentation
./get-wiki || fatal "Error getting wiki documentation"

./ant.sh dist || fatal "Error building distribution"

