#!/bin/sh

debug() { ! "${log_debug-false}" || log "DEBUG: $*" >&2; }
log() { printf '%s\n' "$*"; }
warn() { log "WARNING: $*" >&2; }
error() { log "ERROR: $*" >&2; }
fatal() { error "$*"; exit 1; }
mydir=$(cd "$(dirname "$0")" && pwd -L) || fatal "Unable to determine script directory"

if [ -z "${WORKSPACE}" ]; then
    fatal "WORKSPACE not defined, cannot continue"
fi

cd "${WORKSPACE}"

env

log "Java is: $(type -p java)"
log "Javac is : $(type -p javac)"


#clean up from previous run
git clean -xdf || fatal "Unable to clean workspace"

cd scoring
./ant.sh continuous || fatal "Error running continuous integration tests"

